### PR TITLE
Added Forge item tags for block items.

### LINKED ISSUE #21: Ores lack proper forge item tags
Ores variants added by the mod are lacking proper forge item tags, which makes processing them in various technological mods impossible.
For example, iron ore variants should have tags:
"forge:ores"
"forge:ores/iron"
**NOTE**: They have those tags as **blocks**, but lack them as **items**.

### PR DESCRIPTION
**Pull request by Harleyoc1**
Copy Forge block tags over to block items, fixes #21.

### CODE REVIEW

**Comment by Harleyoc1** [comment]
For anyone who wants this issue without waiting for an update, I originally made this as a data pack for a server so you can use this with the current version: [SubterraneanWildernessItemTags.zip](https://github.com/Melonslise/Subterranean-Wilderness/files/6062304/SubterraneanWildernessItemTags.zip)

**Comment by PaintNinja** [comment]
Thanks for your PR! Please could you provide some short steps to reproduce the issue so that I can verify that it's fixed?

**Comment by Harleyoc1** [comment]
I'm not 100% on whether there is a proper way to test it, but [here's](https://gist.github.com/Harleyoc1/ef9d0b2b5ec37837d4bbbfb7bc428f26) a simple class I wrote that adds the forge tags for each item onto a tooltip which you could add for testing if you want to check they are being applied to the items in the dev environment. 

The other option of course is to just build it and install literally any ore processing mod like Mekanism and you will see that you can now put the ores into the machines and they are processed as would be expected.

**Comment by PaintNinja** [comment]
Confirmed that without this patch, SubWild ores such as Blackstone Iron Ore cannot be processed in certain machinery, such as Mekanism's Enrichment machine.

**Pull request merged**
