### PR TITLE
Mc1.17 port

### PR DESCRIPTION
**Pull request by AfterRebelion**
This is a preliminary update to 1.17, is NOT a complete port, as seen by the pending changes.
Generation unexpectedly works correctly with not much changes

#### Major changes:
- Capabilities no longer have storage: (https://github.com/MinecraftForge/MinecraftForge/issues/7622)

#### Minor changes:
- Using mojmap, so there are a lot of classess/method name changes
- Removed AT on WorldDecoratingHelper/DecorationContext World/Level, as it now has a getter

#### Pending changes
- Adapt to the removal of harvestLevel/harvestTool
- Adapt to different world heights
- Modify Ores drops for iron and gold to use the new Raw Iron/Gold
- Any other change related to 1.17

I don't really pretend to implement this changes. This was only made as a test, and since I already had the changes on local, no harm in making it a PR.

To end, a screenshot of Deepslate and Blackstone generating in the world with Speleothems.
imagen

### CODE REVIEW

**Comment by PaintNinja** [comment]
Thanks for your port! I've left it open for a while in hopes that Melonslise would look at it and finish it off but he seems busy.

If you could implement the "Modify Ores drops for iron and gold to use the new Raw Iron/Gold" pending change I'll accept and publish to CurseForge. :)

**Comment by AfterRebelion** [comment]
Sure! Let me look at it over the weekend.

**Comment by PaintNinja** [comment]
Hey @AfterRebelion, just wanted to ask how it's going?

**Comment by Melonslise** [comment]
I'll try to do it next month

**Comment by MagmaBro123** [comment]
> I'll try to do it next month

2 years later.

**Comment by PaintNinja** [comment]
I'm going to merge this in and get a beta published. Better late and incomplete than never.

**Comment by MagmaBro123** [comment]
1.18 did a great job with caves, but this mod REALLY could improve them a lot more. Not sure why you left it for over 2 years. (I know IRL exists, but still.)

**Comment by MagmaSlime123** [comment]
> I'm going to merge this in and get a beta published. Better late and incomplete than never.

1.18 did a great job with caves, but this mod REALLY could improve them a lot more. Not sure why it was left for over 2 years to rot. (I know IRL exists, but still.)

**Pull request merged**
